// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwR1MtjVqVbk-CHZG3Y4L-P5Na8qAnzC4',
    appId: '1:546459996608:web:00c07785d30a1d7fecb825',
    messagingSenderId: '546459996608',
    projectId: 'esp8266-bad9c',
    authDomain: 'esp8266-bad9c.firebaseapp.com',
    databaseURL: 'https://esp8266-bad9c-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-bad9c.appspot.com',
    measurementId: 'G-M04JXCMWZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfeJ42BJpR8_qEq0faRgFY7QpH9kRv1Mw',
    appId: '1:546459996608:android:4cf2b86c65462ab2ecb825',
    messagingSenderId: '546459996608',
    projectId: 'esp8266-bad9c',
    databaseURL: 'https://esp8266-bad9c-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-bad9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_-Qx2qjd66RvTqagrM4GHtQbUCrD9goY',
    appId: '1:546459996608:ios:9b8382ac4fe5c30cecb825',
    messagingSenderId: '546459996608',
    projectId: 'esp8266-bad9c',
    databaseURL: 'https://esp8266-bad9c-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-bad9c.appspot.com',
    iosBundleId: 'com.example.project01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_-Qx2qjd66RvTqagrM4GHtQbUCrD9goY',
    appId: '1:546459996608:ios:8ff2320999305538ecb825',
    messagingSenderId: '546459996608',
    projectId: 'esp8266-bad9c',
    databaseURL: 'https://esp8266-bad9c-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-bad9c.appspot.com',
    iosBundleId: 'com.example.project01.RunnerTests',
  );
}
